apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleflaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleflaskapp
  template:
    metadata:
      labels:
        app: sampleflaskapp
    spec:
      containers:
      - name: sampleflaskapp
        image: johnreygoh/sampleflaskapp:latest
        ports:
        - containerPort: 5000


